//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyShopping.Repository.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public Nullable<int> SentID { get; set; }
        public Nullable<int> FromID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> MessageType { get; set; }
        public Nullable<int> DataID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual MessageType MessageType1 { get; set; }
    }
}
