//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyShopping.Repository.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipperRating
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ShipperID { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Comment { get; set; }
    
        public virtual User User { get; set; }
        public virtual ShipperDetail ShipperDetail { get; set; }
    }
}
