//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyShopping.Repository.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public int ID { get; set; }
        public Nullable<int> ProductTypeId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
